config/routes.rb
Rails.application.routes.draw do

 namespace :admin do
    # Add dashboard for your models here
    resources :projects
   

    root to: "projects#index" # <--- Root route
  end

	root 'pages#index'
		get  '/works',   to: 'projects#index'
	  	get  '/info',   to: 'pages#info'
  		get  '/contact', to: 'pages#contact'
  		get '/projects/:title', to: "projects#show"
  		resources :projects
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
	class Project < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: [:slugged, :finders]
	validates :title, presence: true, length: { minimum: 3 }
  	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	validates_attachment_size :image, :in => 0.megabytes..15.megabytes
	has_attached_file :projectimg, styles: { medium: "300x300>", thumb: "100x100>" }
        validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	has_attached_file :projectimg2, styles: { medium: "300x300>", thumb: "100x100>" }
        validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  	

	def next
	    Project.where("id < ?", id).order("id DESC").first || Project.last
	end

	def previous
	    
	    Project.where("id > ?", id).order("id ASC").first || Project.first
	end

	

	def should_generate_new_friendly_id? #will change the slug if the name changed
    	title_changed?
  end

	 def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Project.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Project.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 respond_to :html, :js
	  def index
		@project = Project.find(params[:id])
		project.next = Project.where("id > ?", id).order("id ASC").first || Project.first
   		project.previous = Project.where("id < ?", id).order("id DESC").first || Project.last
  		
  		
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	respond_to :html, :js

		def index
			@projects = Project.all.order(created_at: :desc)
			@project = Project.first
			 respond_to do |format|
					format.html
					format.js
				end
		end
	
		def info
			respond_to do |format|
				format.html
				format.js
			end
		end

		def contact
			respond_to do |format|
				format.html # index.html.erb
				format.js
			end
		end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  # GET /projects
  # GET /projects.json
  def index
    
  @projects = Project.order('created_at DESC')
  respond_to do |format|
      format.html { render 'projects/index' }
      format.js
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
   @project = Project.friendly.find(params[:title])
  # @credits = JSON.parse(@project.credits)
  respond_to do |format|
      format.html { render 'projects/show' }
      format.js
  end
  end


  # GET /projects/new

def edit
    @project = Project.find params[:id]
  end

  # POST /products
  # POST /products.json
  def create
    @project = Project.new(product_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @project.category_id = params[:category_id]
    respond_to do |format|
      if @project.update(product_params)
        format.html { redirect_to @project, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # POST /projects
  # POST /projects.json


  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json

  # DELETE /projects/1
  # DELETE /projects/1.json


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
     
     @project = Project.friendly.find(params[:title])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.fetch(:project, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "DEADBUTCOOL"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      page_title + " | " + base_title                 # String concatenation
    end
  end

  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/remote_link_pagination_helper.rb
require 'will_paginate/view_helpers/link_renderer'
require 'will_paginate/view_helpers/action_view'
module RemoteLinkPaginationHelper
  class LinkRenderer < WillPaginate::ActionView::LinkRenderer
    def link(text, target, attributes = {})
      attributes['data-remote'] = true
      super
    end
  end
end

app/views/fields/paperclip_field/_form.html.erb
<%= f.label field.attribute %>
<%= f.file_field field.attribute %>

app/views/fields/paperclip_field/_index.html.erb
# app/views/fields/paperclip_field/_index.html.erb
<%= image_tag field.thumbnail %>

app/views/fields/paperclip_field/_show.html.erb
# app/views/fields/paperclip_field/_show.html.erb
<%= image_tag field.url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>DEAD BUT COOL</title>
    
   <%= render 'partials/meta' %>

  </head>

  <body>
  <%= render "partials/header" %>

  <div id="maincontent" class="fade-in" data-fade-delay="250">
    <%= yield %>
  </div>

  <div class="push"></div>
	<div id="footer">
		<p><br/></p>
	</div>

  <%= javascript_include_tag 'application' %>

  </body>


</html>

app/views/pages/contact.html.erb
<% provide(:title, "CONTACT") %>
<div class="static-contact">
<div class="content">
	<div class="mailandtel">
  <h1 style="margin:0;">
  	General inquiries:
	<a href="mailto:info@deadbutcool.com"><h1 class="contact-link">info@deadbutcool.com</h1></a>
	<br>
	Business inquiries:
	<a href="mailto:hello@deadbutcool.com"><h1 class="contact-link">hello@deadbutcool.com</h1></a>
	<br>
	<a href="tel:+7-322-674-88-03"><h1 class="contact-link">Tel.: +7 322 674 88 03</h1></a>
	</h1></div>

	<div class="info">
		<p id="column1">We always looking forward to communicate.  Don’t hesitate to write us directly
		<p >Or keep in touch via <span class="facebook">Facebook</span>, <span class="soundcloud">  Soundcloud</span> or <span class="youtube">Youtube</span>
	</div>

</div>

</div>

app/views/pages/index.html.erb
<div>
<div class="static fade-in" data-fade-delay="1000">
  <h1>Independent studio crafting sound-design and music for Fendi, Mercedes, Durex, Adidas and <a href="/works" style="word-wrap: break-word;color: white;font-family: Favorit_Regular;font-style: normal;font-stretch: normal;font-weight:100;line-height: 1;letter-spacing: normal;font-size: inherit;border-bottom: 4px solid #fff;display: inline-block;">more</a></h1>
</div>
<div id="slider-wrapper" class="loading"  style="position:relative;">
  <div id="curtain" style=" z-index: 2; position: absolute; top:0; cursor: default; ">
  </div>
<div id="empty-space" style="position: absolute; z-index: 1;
    bottom: 0;
    height:100%;
    width: 100%;
    cursor: pointer;
    ">
  </div>
  <div class="slider" style="position:relative;">
    <% @projects.each_with_index do |project, index| %>
      <li>
        <div class="top" style="position:relative;">
          <div class="wrapper" data-title="<%= project.title.upcase %>" data-title-next="<%= project.next.title.upcase %>" data-title-prev="<%= project.previous.title.upcase %>" style="position:relative;">
              <div class='video' data-video-id="<%= project.link %>"></div>
          </div>
        </div>
        <%= link_to "VIEW PROJECT CASE", project_path(project), class: 'viewcase', style: "display:none;" %>
      </li>
    <% end %>
  </div>
 
<div class="bottom-left bx-prev fade-in" data-fade-delay="2250">
  <img class="slider-controls" src="assets/icon-previous-mobile@3x.png" alt="Icon previous mobile@3x" width="100" height="50" />
</div>
  <div class="bottom-center fade-in" data-fade-delay="1500">
    <div id="playpause" class="play"> </div>
  </div>
  <div class="bottom-right bx-next fade-in" data-fade-delay="2250">
    <img class="slider-controls" src="assets/icon-next-mobile@3x.png" alt="Icon next mobile@3x" width="100" height="50" />
  </div>

  <p class="project-title top-left" style="left:0;">
    <span id="title-prev"></span>
  </p>

  <div class="project-title top-center" >
    <p id="top-center" class="fade-in"  style=" display: inline-block;line-height:1;">
      <img id="setvolume" src="assets/DBC_SOUNDOFF.svg" />
      <span id="title"></span>
    </p>
    
  </div>
  <p class="project-title top-right" style="right:0;">
    <span id="title-next"></span>
  </p>

</div>
</div>



<style>
 .control-left {
    width:150px;
  /*max-width: 8em; блок занимает ширину родителя, max-width её ограничивает */
  min-height: 2em;

  margin-right: 0;
 }
 .control-right  {  
  width:150px;
  /*max-width: 8em; блок занимает ширину родителя, max-width её ограничивает */
  min-height: 2em;

  margin-right: 0;
}
.section {
  width:100%;
  

  z-index:4545;
  position: absolute;
  bottom: 40%;
}

/*  COLUMN SETUP  */
.col {
  display: inline-block;
  
  

}



/*  GO FULL WIDTH BELOW 480 PIXELS */

</style>
















  
  













app/views/pages/info.html.erb
<% provide(:title, "INFO") %>

<div class="static-info">
	<div class="independent">
   		<h1>Independent studio crafting sound-design for Fendi, Chanel, Saint-Lauren  and <span><a href="/works"><h1 id="works-link">more</h1></a></span></h1></div>

<div class="info">
			<p>We are the studio specialized in commercial audio
for tv, radio and digital media. We consider interaction 
with a viewer as an art. Visuality breathes through 
sound and silence. Each viewer has got the 
heartbeat. So does the picture. We let them concur.  

<br>

<p>The future of the moving pictures starts with the
shot. The moment. It all has got its own personality. 
Its colours and flavours. Its voice. Every project we 
touch already has a voice. 
We let you hear it.
	</div>
</div>

  

app/views/partials/_footer.html.erb
<div class="push"></div>
<div id="footer">
	<p><br></p>
</div>

app/views/partials/_header.html.erb
<ul id="header" class="fade-in" data-fade-delay="500">
  <div style="position: relative">
    <div class="logo-right"><a href="/" style="font-family:Canela-Light;font-weight:100;text-decoration:none;">DEAD BUT COOL</a></div>
  </div>
  <div id="deskmenu" class="navigation navigation-desk navigation-tablet navigation-main">
    <li><%= link_to "WORKS", works_path, class: 'nav' %></li>
    <li><%= link_to "INFO", info_path, class: 'nav' %></li>
    <li><%= link_to "CONTACT", contact_path, class: 'nav' %></li>
  </div>
  <div class="navigation navigation-mobile navigation-main">
    <li id="menu-toggle" class="openbtn" >MENU</li>
  </div>
  <div id="deskmenu-project" class="navigation navigation-mobile navigation-desk navigation-tablet navigation-project">
    <li><a id="viewcase" href="#" >VIEW PROJECT CASE</a></li>
    <li><a id="closebtn" style="right: 0;" onclick="return false;"> CLOSE</a></li>
  </div>

</ul>
   <div id="myNav" class="overlay">

  <div class="overlay-content">
     <%= link_to "WORKS", works_path %>
     <%= link_to "INFO", info_path, id: "info" %>
     <%= link_to "CONTACT", contact_path, id: "contact" %>
  </div>

  <div class="social" style="white-space: nowrap;display: inline-block;">
    <p> <span class="youtube">YOUTUBE</span>&nbsp;<span class="facebook">FACEBOOK</span>&nbsp;<span class="soundcloud">SOUNDCLOUD</span></p>
  </div>
</div>

app/views/partials/_meta.html.erb
	<%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
     <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <%= stylesheet_link_tag 'application', media: 'all' %>

app/views/projects/index.html.erb
<div class="grid">
  <% @projects.each do |project| %>

    <div class="img-item">

		<% if project.image.present? %>
		 
		<%= link_to (image_tag(project.image, class: 'img-responsive')), project, class: 'gallery' %> 

		 	<%= link_to(project) do %> 
				    <p class="brand">
				    	<%= project.brand.upcase %>
				    </p>
			<% end %> 

		<% else  %>

	<%= link_to(project) do %> 

				<div class="container">

					<div class="marquee">
						<h2><%= project.brand.upcase %></h2>

						<p><%= project.category %>
					</div>

					<div class="marquee" data-direction='right'>
						<h2><%= project.brand.upcase %></h2>

						<p><%= project.category %>
					</div>
					
					<div class="marquee">
						<h2><%= project.brand.upcase %></h2>

						<p><%= project.category %>
						</div>
					
					<div class="marquee" data-direction='right'>
						<h2><%= project.brand.upcase %></h2>

						<p><%= project.category %>
					</div>

					<div class="marquee">
						<h2><%= project.brand.upcase %></h2>

						<p><%= project.category %>
					</div>
					<div class="marquee" data-direction='right'>
                                                <h2><%= project.brand.upcase %></h2>

                                                <p><%= project.category %>
                                        </div>	
									

				</div>

			<% end %>
		<% end %>

	</div>
   
  <% end %> 

</div>

app/views/projects/show.html.erb
	
<div class="project-top">
  <div id="slider-wrapper" class="loading"  style="position:relative;">
    <div style="position: absolute; z-index: 1;
        bottom: 0;
        height:100%;
        width: 100%;
    ">
    </div>
    <div style="width: 100%; overflow: hidden; position: relative; ">
      <li style="width: 100%;">
        <div class="top" style="position:relative;">
          <div class="wrapper" style="position:relative;">
            <iframe src="https://player.vimeo.com/video/<%= @project.link %>?title=0&byline=0&portrait=0&transparent=0&color=ffffff" width="640" height="480" frameborder="0"  webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" data-ready="true"></iframe>
          </div>
        </div>
      </li>
    </div>
    <div class="bottom-center fade-in" data-fade-delay="1500">
      <div id="playpause" class="play"> </div>
    </div>
  </div>
</div>

<div class="proj--container">

<h1 class="proj-title"><%= @project.title %></h1>

<div class="info">
    <%= simple_format(@project.description, {}, wrapper_tag: "p") %>
</div>

<% if @project.projectimg? %>
    <div class="img_wrap">
        <%= image_tag @project.projectimg, class: 'project_img' %>
    </div>
<% else %>
　　 <%= nil %>
<% end %>

<% if @project.description2? %>
　　<div class="info"> 
    <%= simple_format(@project.description2, {}, wrapper_tag: "p") %>
</div>
　<% else %>
　　<%= nil %>
<% end %>

<% if @project.projectimg2? %>
  <div class="img_wrap">
    <%= image_tag @project.projectimg2, class: 'project_img' %>
  </div>
<% else %>
　　 <%= nil %>
<% end %>

<div class="credits">


  <h1>Credits:<br>
<%if @project.credit1? %>
<% a = @project.credit1.split(":") %>

  <%= a[0] %>: 
  <%if @project.link1? %> 
  <%= link_to a[1], "#{@project.link1}", target: "_blank" %>
     <% else %>
       <%= a[1] %>
 <% end %><br>
<% end %>


<%if @project.credit2? %>
<% b = @project.credit2.split(":") %>

  <%= b[0] %>: 
  <%if @project.link2? %> 
  <%= link_to a[1], "#{@project.link2}", target: "_blank" %>
     <% else %>  
     <%= b[1] %>
 <% end %><br>
<% end %>

<%if @project.credit3? %>
<% c = @project.credit3.split(":") %>

  <%= c[0] %>: 
  <%if @project.link3? %> 
  <%= link_to c[1], "#{@project.link3}", target: "_blank" %>
     <% else %>  
     <%= c[1] %>
 <% end %><br>
<% end %>

<%if @project.credit4? %>
<% d = @project.credit4.split(":") %>

  <%= d[0] %>: 
  <%if @project.link4? %> 
  <%= link_to d[1], "#{@project.link4}", target: "_blank" %>
  <% else %>
  <%= d[1] %>
 <% end %><br>
<% end %>


<%if @project.credit5? %>
<% e = @project.credit5.split(":") %>

  <%= e[0] %>: 
  <%if @project.link5?  %> 
  <%= link_to e[1], "#{@project.link5}", target: "_blank" %>
   <% else %>  
   <%= e[1] %>
 <% end %><br>
<% end %>

<%if @project.credit6? %>
<% f = @project.credit6.split(":") %>

  <%= f[0] %>: 
  <%if @project.link6?  %> 
  <%= link_to f[1], "#{@project.link6}", target: "_blank" %>
     <% else %>
     <%= f[1] %>
 <% end %><br>
<% end %>

<%if @project.credit7? %>
<% g = @project.credit7.split(":") %>

  <%= g[0] %>: 
  <%if @project.link7?  %> 
  <%= link_to g[1], "#{@project.link7}", target: "_blank" %>
    <% else %> 
    <%= g[1] %>
 <% end %><br>
<% end %>


<%if @project.credit8? %>
<% h = @project.credit8.split(":") %>

  <%= h[0] %>: 
  <%if @project.link8? %> 
  <%= link_to h[1], "#{@project.link8}", target: "_blank" %>
    <% else %> 
    <%= h[1] %>
 <% end %><br>
<% end %>




<%if @project.credit9? %>
<% i = @project.credit9.split(":") %>

  <%= i[0] %>: 
  <%if @project.link9?  %> 
  <%= link_to i[1], "#{@project.link9}", target: "_blank" %>
   <% else %>  
   <%= i[1] %>
 <% end %><br>
<% end %>


<%if @project.credit10? %>
<% j = @project.credit10.split(":") %>

  <%= j[0] %>: 
  <%if @project.link10? %> 
  <%= link_to j[1], "#{@project.link10}", target: "_blank" %>
    <% else %> 
     <%= j[1] %>
 <% end %><br>
<% end %>

</h1>




</div>

<div class="container--flex" id="prev-next-brand">
<div class="flex-child" style="float:right;text-align: right;width:50%;">
    <%= link_to(project_url(@project.next)) do %>
                <div>
                    <p>  <%= @project.next.brand.upcase %>
                </div>
                <% end %>
</div>

</div>

<!-- PREVIOUS/NEXT on >=TABLET  view end
-->
<div class="container--flex" id="prev-next">
  <%= link_to(project_url(@project.previous)) do %>
                <div>
                     <p style="text-decoration: none;">PREVIOUS PROJECT
                </div>
                <% end %>
<div class="flex-child">
  
</div>


<div class="flex-child" style="text-align: right;">
    <%= link_to(project_url(@project.next)) do %>
                <div>
                     <p style="text-decoration: none;"> NEXT PROJECT
                </div>
                <% end %>
</div>

</div>







<div class="container--flex">
  <div class="flex-child" style="max-width: 100px;"> <div><%=   link_to (image_tag("icon-previous-mobile@3x.png", id: 'control-img', class: 'control', :style => "float:left;line-height:1em;", size: "100x50")), project_url(@project.previous) %>
</div></div>
  <div class="flex-child" style="margin-left:30px;max-width: 440px;text-align: left;word-break: break-all;">
    <%= link_to(project_url(@project.previous)) do %>
                <div class="brandlink">
                    <p style="    margin-bottom: 0px;text-decoration: none;"> <%= @project.previous.brand.upcase %>
                </div>
                <% end %>

</div>
   <div class="flex-child" style="width: auto;"></div>
    <div class="flex-child" style="margin-right:30px;max-width: 440px;text-align: right;word-break: break-all;">
    <%= link_to(project_url(@project.next)) do %>
                <div class="brandlink">
                    <p style="    margin-bottom: 0px;text-decoration: none;"> <%= @project.next.brand.upcase %>
                </div>
                <% end %>

</div>
   <div class="flex-child" style="max-width: 100px;"><div style="float:right;"> 
    <%= link_to (image_tag("icon-next-mobile@3x.png", id: 'control-img', class: 'control', :style => "float:right;line-height:1em;", size: "100x50")), project_url(@project.next) %>
</div></div>
</div>




</div>
<style>
  #maincontent {
    padding: 0 !important;
  }
</style>